### ISSUE TITLE
some right-click functions not working

### ISSUE THREAD

**Issue by jerole** [dimensionsintime/TorchPlaceMod#6]
Hello again!

After using the mod for several days we encountered a few issues with some tools/items not working properly anymore. For example the right-click functions of shovels and the TC mattock are not working anymore, the shovels won't turn grass into perma dirt blocks and the mattock won't hoe dirt. Bibliocraft labels also don't work, shift-click doesn't open the interface.

Maybe it would be useful to be able to create some kind of blacklist for those items with which the mod won't trigger.

**Comment by dimensionsintime** [comment]
Hopefully get to work on mods some more tomorrow (6-23)

**Comment by dimensionsintime** [comment]
Hi. The mod does have a block and item check routine so I can blacklist things internally. Will think about opening that up to the config, the user would need to know the item or block registry name in order to blacklist as it's set up now, which might not be ideal. Anyway, turning off shovels and hoes, and will go through TC and Biblio (maybe some other popular mods too) and add terms to help with problems like this. New release coming.

**Comment by dimensionsintime** [comment]
Beta 0.9 released to solve these issues. Adds config options to blacklist items, blocks or items that only work with dirt blocks (allows them to place on other blocks, but not dirt/grass/etc).
